coverage:
  range: 70..80
  round: up
  precision: 2

ignore:
  - 'client/src/components/*'
  - 'client/src/assets/*'
  - 'client/src/routes'
  - 'client/Firebase.js'
  - 'client/index.js'
  - 'client/App.js'