name: CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.8.1'

    - name: Install dependencies
      run: |
        cd client
        npm install --legacy-peer-deps

    - name: Run tests with coverage
      run: |
        cd client
        npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        path: client/coverage/lcov.info
