name: CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.8.1'

    - name: Install dependencies
      run: |
        cd client
        npm install --legacy-peer-deps

    - name: Run tests with coverage
      run: |
        cd client
        npm test -- --coverage

    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: | 
       curl -Os https://uploader.codecov.io/latest/linux/codecov
       find . -iregex "codecov.*"
       chmod +x codecov 
       ./codecov -t ${CODECOV_TOKEN}
